# General
ON = 1
RUN = ON
START = ON
OFF = 0
STOP = OFF

# Acquisition
ACQ_STATE = ':ACQuire:STATE'
ACQ_MODE = ':ACQuire:STOPAfter'
ACQ_MODE_RUNSTOP = 'RUNSTop'
ACQ_MODE_SEQUENCE = 'SEQuence'

# Horizontal
FASTFRAME_STATE = ':HORizontal:FASTframe:STATE'
FASTFRAME_COUNT = ':HORizontal:FASTframe:COUNt'
FASTFRAME_COUNT_MAX = ':HORizontal:FASTframe:MAXFRames'

# Miscellaneous
HEADER = ':HEADer'

#Save and Recall
TEK_HOME_FOLDER_PATH = 'C:\\Users\\Tek_Local_Admin\\Tektronix\\TekScope'
LOAD_SETUP = ':RECAll:SETUp'
FACTORY_SETUP = 'FACtory'
SAVE_SETUP = ':SAVe:SETUp'
SAVE_SETUP_INCLUDEREFS = ':SAVe_SETUp_INCLUDEREFs'

# SaveOn
SAVEON_TRIGGER = ':SAVEON:TRIGger'
SAVEON_TRIGGER_FILE_PATH = ':SAVEON:FILE:DEST'
SAVEON_TRIGGER_FILE_NAME = ':SAVEON:FILE:NAME'
SAVE_WAVEFORM_ON_TRIGGER = ':SAVEON:WAVEform'
SAVEON_TRIGGER_WAVEFORM_SOURCE = ':SAVEON:WAVEform:SOURce'
